spring.application.name=LibraryManagementSys
spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root
spring.datasource.password=ROhan@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa-sql=true